import os


class GameConstants:
    SCREEN_SIZE = (1080, 720)
    # SCREEN_SIZE = (800, 600)
    FPS = 60
    INTERVAL = .15  # animation interval

    SIZE_RATIO = 6

    STARTING_SCENE = 0

    """ Define Types """
    GAME_OBJECT = 0
    PLAYER_OBJECT = 1
    COMPUTER_OBJECT = 2

    """ SCREEN DIVISION CONSTANTS """
    # X
    BATTLE_AREA_PLAYER_BORDER = int(SCREEN_SIZE[0] * 3 / 8)  # 300
    BATTLE_AREA_COMPUTER_BORDER = (SCREEN_SIZE[0] - BATTLE_AREA_PLAYER_BORDER)  # 500
    # Y
    BATTLE_AREA_TOP = int(SCREEN_SIZE[1] / 3)  # 200
    BATTLE_AREA_BOTTOM = int(SCREEN_SIZE[1] * 2 / 3)  # 400

    PADX = 50
    PADY = 25

    """ PLAYER AREA """
    PLAYERS_BACK_COLUMN = int(SCREEN_SIZE[0] * 3 / 32)
    PLAYERS_FRONT_COLUMN = int(SCREEN_SIZE[0] * 8 / 32 + PADX)
    PLAYERS_TOP_ROW = int(SCREEN_SIZE[1] * 5 / 12 - 3 * PADY)
    PLAYERS_MIDDLE_ROW = int(SCREEN_SIZE[1] / 2 - 2 * PADY)
    PLAYERS_BOTTOM_ROW = int(SCREEN_SIZE[1] * 7 / 12 - PADY)

    # Playing Scene CENTER Positions
    PLAYER_TOP_BACK = (PLAYERS_BACK_COLUMN, PLAYERS_TOP_ROW)
    PLAYER_MIDDLE_BACK = (PLAYERS_BACK_COLUMN, PLAYERS_MIDDLE_ROW)
    PLAYER_BOTTOM_BACK = (PLAYERS_BACK_COLUMN, PLAYERS_BOTTOM_ROW)

    PLAYER_TOP_FRONT = (PLAYERS_FRONT_COLUMN, PLAYERS_TOP_ROW)
    PLAYER_MIDDLE_FRONT = (PLAYERS_FRONT_COLUMN, PLAYERS_MIDDLE_ROW)
    PLAYER_BOTTOM_FRONT = (PLAYERS_FRONT_COLUMN, PLAYERS_BOTTOM_ROW)

    """ COMPUTER AREA """
    COMPUTER_BACK_COLUMN = int(SCREEN_SIZE[0] - PLAYERS_BACK_COLUMN)
    COMPUTER_FRONT_COLUMN = int(SCREEN_SIZE[0] - PLAYERS_FRONT_COLUMN)

    # Playing Scene CENTER Positions
    COMPUTER_TOP_BACK = (COMPUTER_BACK_COLUMN, PLAYERS_TOP_ROW)
    COMPUTER_MIDDLE_BACK = (COMPUTER_BACK_COLUMN, PLAYERS_MIDDLE_ROW)
    COMPUTER_BOTTOM_BACK = (COMPUTER_BACK_COLUMN, PLAYERS_BOTTOM_ROW)

    COMPUTER_TOP_FRONT = (COMPUTER_FRONT_COLUMN, PLAYERS_TOP_ROW)
    COMPUTER_MIDDLE_FRONT = (COMPUTER_FRONT_COLUMN, PLAYERS_MIDDLE_ROW)
    COMPUTER_BOTTOM_FRONT = (COMPUTER_FRONT_COLUMN, PLAYERS_BOTTOM_ROW)

    """ Menus """
    PLAYER_UNITS_MENU_WIDTH = PLAYERS_FRONT_COLUMN + 1 * PADX
    COMPUTER_MODELS_MENU_WIDTH = SCREEN_SIZE[0] - COMPUTER_FRONT_COLUMN + PADX

    """ BACKGROUNDS """
    ASSETS_GFX_PATH = os.path.join("Assets", "Graphics")
    ASSETS_GFX_BACKGROUNDS_PATH = os.path.join(ASSETS_GFX_PATH, "Backgrounds")
    MAIN_MENU_BACKGROUND = os.path.join(ASSETS_GFX_BACKGROUNDS_PATH, "main_menu_background.jpg")
    DARK_LAIR = os.path.join("Assets", "Graphics", "dark_lair.png")
    CAVE_TILE = os.path.join("Assets", "Graphics", "cave_tile.png")

    """ COLORS """
    WHITE = (255, 255, 255)
    BLACK = (0, 0, 0)
    BRIGHT_RED = (255, 0, 0)
    RED = (155, 0, 0,)
    BRIGHT_GREEN = (0, 255, 0)
    GREEN = (0, 155, 0)
    BRIGHT_BLUE = (0, 0, 255)
    BLUE = (0, 0, 155)
    BRIGHT_YELLOW = (255, 255, 0)
    YELLOW = (155, 155, 0)
    BRIGHT_GRAY = (128, 128, 128)
    DARK_GRAY = (40, 40, 40)
    CYAN = (0, 255, 255)

    """ TARGETING """
    TARGET_PLAYER_SINGLE_ANY = 0
    TARGET_PLAYER_SINGLE_FRONT = 1
    TARGET_PLAYER_SINGLE_BACK = 2
    TARGET_PLAYER_ALL = 3
    TARGET_PLAYER_ALL_FRONT = 4
    TARGET_PLAYER_ALL_BACK = 5

    TARGET_COMPUTER_SINGLE_ANY = 6
    TARGET_COMPUTER_SINGLE_FRONT = 7
    TARGET_COMPUTER_SINGLE_BACK = 8
    TARGET_COMPUTER_ALL = 9
    TARGET_COMPUTER_ALL_FRONT = 10
    TARGET_COMPUTER_ALL_BACK = 11
